import React, { useState } from 'react';
import { Copy, Check, Download, FileCode, X, Sparkles, ExternalLink, Globe, Link2, ArrowRight } from 'lucide-react';
import { FuturisticScrollTrack } from './FuturisticScrollTrack.tsx';

export interface GeneratedContentData {
  title: string;
  contentType: 'code' | 'prompt' | 'text' | 'link';
  language?: string;
  content: string;
  url?: string;
  summary?: string;
}

interface GeneratedContentModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: GeneratedContentData | null;
}

export const GeneratedContentModal: React.FC<GeneratedContentModalProps> = ({
  isOpen,
  onClose,
  data,
}) => {
  const [isCopied, setIsCopied] = useState(false);

  if (!isOpen || !data) return null;

  const isLink = data.contentType === 'link' || (data.content.startsWith('http://') || data.content.startsWith('https://'));
  const targetUrl = isLink ? (data.url || data.content.trim()) : '';

  const handleCopy = () => {
    navigator.clipboard.writeText(isLink ? targetUrl : data.content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2500);
  };

  const handleOpenLink = () => {
    if (targetUrl) {
      window.open(targetUrl, '_blank', 'noopener,noreferrer');
    }
  };

  const handleDownload = () => {
    const ext = getExtension(data.language || 'txt');
    const filename = `${data.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}.${ext}`;
    const blob = new Blob([data.content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getExtension = (lang: string) => {
    const l = lang.toLowerCase().trim();
    if (l.includes('py')) return 'py';
    if (l.includes('javascript') || l === 'js') return 'js';
    if (l.includes('typescript') || l === 'ts') return 'ts';
    if (l.includes('html')) return 'html';
    if (l.includes('css')) return 'css';
    if (l.includes('json')) return 'json';
    if (l.includes('md') || l.includes('markdown')) return 'md';
    return 'txt';
  };

  const lines = data.content.split('\n');

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-black/85 backdrop-blur-md animate-motion-blur-in">
      <div className="w-full max-w-3xl max-h-[90vh] bg-slate-900 border border-cyan-500/40 rounded-2xl shadow-[0_0_40px_rgba(6,182,212,0.25)] flex flex-col overflow-hidden relative motion-blur-glass">
        {/* Top Glow Accent */}
        <div className="absolute -top-16 -left-16 w-36 h-36 bg-cyan-500/20 rounded-full blur-3xl pointer-events-none" />

        {/* Modal Header */}
        <div className="px-4 py-3.5 bg-slate-950/90 border-b border-cyan-500/25 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-cyan-500 to-blue-600 flex items-center justify-center shadow-md shadow-cyan-500/30">
              {isLink ? <Globe className="w-4 h-4 text-white" /> : <Sparkles className="w-4 h-4 text-white" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-sm sm:text-base text-white tracking-tight">
                  {data.title || (isLink ? 'Web Link' : 'Generated Output')}
                </h3>
                <span className="text-[10px] font-mono uppercase font-bold px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-300 border border-cyan-500/30">
                  {isLink ? 'LINK / URL' : data.language ? data.language.toUpperCase() : 'CODE / PROMPT'}
                </span>
              </div>
              <p className="text-[11px] text-cyan-400/70 font-mono">
                {isLink ? 'Interactive Link Card • Tap to Open or Copy' : 'Generated by Iris • Ready to copy or save'}
              </p>
            </div>
          </div>

          {/* Top-Right Action Controls */}
          <div className="flex items-center gap-2">
            {isLink ? (
              <button
                onClick={handleOpenLink}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl font-bold text-xs bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 shadow-md shadow-cyan-500/30 transition-all active:scale-95"
              >
                <ExternalLink className="w-3.5 h-3.5 text-slate-950" />
                <span>Open Website</span>
              </button>
            ) : null}

            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl font-medium text-xs transition-all active:scale-95 shadow-md ${
                isCopied
                  ? 'bg-emerald-600 text-white shadow-emerald-500/30'
                  : 'bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold shadow-cyan-500/30'
              }`}
              title="Copy to clipboard"
            >
              {isCopied ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy {isLink ? 'Link' : data.contentType === 'prompt' ? 'Prompt' : 'Code'}</span>
                </>
              )}
            </button>

            {!isLink && (
              <button
                onClick={handleDownload}
                className="hidden sm:flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium transition-colors"
                title="Download file"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Save</span>
              </button>
            )}

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition-colors ml-1"
              title="Close Popup"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body: Link View or Code/Prompt View */}
        {isLink ? (
          <div className="p-6 bg-slate-950 space-y-4">
            <div className="p-4 rounded-xl bg-slate-900/90 border border-cyan-500/30 shadow-inner flex flex-col space-y-3">
              <div className="flex items-center gap-2 text-cyan-300 text-xs font-mono">
                <Link2 className="w-4 h-4 text-cyan-400" />
                <span>DIRECT DESTINATION URL</span>
              </div>

              <div className="p-3 rounded-lg bg-slate-950 border border-cyan-500/20 text-cyan-100 font-mono text-sm break-all select-all flex items-center justify-between gap-3">
                <span className="truncate">{targetUrl}</span>
                <button
                  onClick={handleCopy}
                  className="shrink-0 p-1.5 rounded-md bg-cyan-950 text-cyan-300 hover:bg-cyan-900 transition-colors"
                  title="Copy link"
                >
                  <Copy className="w-3.5 h-3.5" />
                </button>
              </div>

              {data.summary && (
                <p className="text-xs text-slate-300 leading-relaxed font-sans">
                  {data.summary}
                </p>
              )}

              <div className="pt-2 flex items-center gap-3">
                <button
                  onClick={handleOpenLink}
                  className="flex-1 py-3 px-4 rounded-xl font-bold text-sm bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 flex items-center justify-center gap-2 shadow-lg shadow-cyan-500/20 transition-all"
                >
                  <span>Launch Link in Browser</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        ) : (
          <FuturisticScrollTrack className="flex-1 bg-slate-950 p-4">
            <div className="flex min-w-full font-mono text-xs sm:text-[13px] leading-relaxed select-text">
              {/* Line numbers gutter */}
              <div className="pr-3 mr-3 border-r border-slate-800 text-slate-600 select-none text-right font-mono text-xs">
                {lines.map((_, i) => (
                  <div key={i}>{i + 1}</div>
                ))}
              </div>
              {/* Code / Prompt text */}
              <pre className="flex-1 overflow-x-auto text-slate-100 whitespace-pre">
                <code>{data.content}</code>
              </pre>
            </div>
          </FuturisticScrollTrack>
        )}

        {/* Modal Footer */}
        <div className="px-4 py-2.5 bg-slate-950/95 border-t border-cyan-500/20 flex items-center justify-between text-xs text-slate-400 shrink-0">
          <div className="flex items-center gap-2 text-[11px] text-cyan-300/80 truncate max-w-[80%]">
            <FileCode className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
            <span className="truncate">
              {isLink ? `Link: ${targetUrl}` : data.summary || `${lines.length} lines generated by Iris`}
            </span>
          </div>
          <button
            onClick={onClose}
            className="text-[11px] font-mono text-cyan-400 hover:text-cyan-200 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
